[package]
name = "mzstatic"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
base64 = "0.22.1"
thiserror = "2.0.17"
maybe_owned_string = { path = "../maybe_owned_string/" }

[features]
std = []
default = ["std"]
