[package]
name = "unaligned_u16"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
ointers = "5.0.0"
thiserror = { version = "2.0.11", default-features = false }

[features]
utf16 = []
alloc = []
